### Get comment by adId
GET http://localhost:8080/ads/2/comments
Content-Type: application/json
Authorization: Basic user1@ya.ru User1234

### Delete comment by adId & commentId
DELETE http://localhost:8080/ads/2/comments/15
Content-Type: application/json
Authorization: Basic user1@ya.ru User1234

### Update comment by adId & commentId
PATCH http://localhost:8080/ads/2/comments/16
Content-Type: application/json
Authorization: Basic user1@ya.ru User1234

{
  "text": "Торг возможен? Купил бы за 987"
}

### Update comment by adId & commentId (Not found Ad)
PATCH http://localhost:8080/ads/20/comments/16
Content-Type: application/json
Authorization: Basic user1@ya.ru User1234

{
  "text": "Торг возможен? Купил бы за 987"
}

### Update comment by adId & commentId (Not found Ad)
PATCH http://localhost:8080/ads/2/comments/76
Content-Type: application/json
Authorization: Basic user1@ya.ru User1234

{
  "text": "Торг возможен? Купил бы за 987"
}

### Update comment by adId & commentId (403 Forbidden)
PATCH http://localhost:8080/ads/2/comments/11
Content-Type: application/json
Authorization: Basic user1@ya.ru User1234

{
  "text": "Торг возможен? Купил бы за 987"
}


### Login admin
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "aleks_413@mail.ru",
  "password": "Renby413"
}

### Login user (Success)
POST http://localhost:8080/login
Content-Type: application/json

{
"username": "user1@ya.ru",
"password": "User1234"
}

### Login user (Bad password - 401)
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "user1@ya.ru",
  "password": "User1234000"
}

###
POST http://localhost:8080/register
Content-Type: application/json

{
  "username": "adUser@gmail.com",
  "password": "password",
  "firstName": " asdad",
  "lastName": " asdad",
  "phone": " asdad",
  "role": "USER"
}

### Get Ads by User
GET http://localhost:8080/ads/me
Content-Type: application/json
Authorization: Basic user1@ya.ru User1234

### Get Ad by adId
GET http://localhost:8080/ads/2
Content-Type: application/json
Authorization: Basic user1@ya.ru User1234

### Delete Ad by  (Forbidden)
DELETE http://localhost:8080/ads/2
Content-Type: application/json
Authorization: Basic user1@ya.ru User1234

### Delete Ad by  (Not found)
DELETE http://localhost:8080/ads/90
Content-Type: application/json
Authorization: Basic user1@ya.ru User1234

### Delete Ad by  (204)
DELETE http://localhost:8080/ads/3
Content-Type: application/json
Authorization: Basic user1@ya.ru User1234

###
GET http://localhost:8080/users/me
Content-Type: application/json
Authorization: Basic adUser@gmail.com password

###
PATCH http://localhost:8080/users/me
Content-Type: application/json
Authorization: Basic adUser@gmail.com password

{
  "phone": "33333",
  "lastName": "Ivanov",
  "firstName": "Ivan"
}

### No Authorization
GET http://localhost:8080/ads
Content-Type: application/json

###
POST http://localhost:8080/users/set_password
Content-Type: application/json
Authorization: Basic adUser@gmail.com password

{
  "newPassword": "password",
  "currentPassword": "password1"
}

###
POST http://localhost:8080/ads
Content-Type: application/json
Authorization: Basic adUser@gmail.com password

{
  "price": 123,
  "description": "123",
  "title": "123"
}

